dataset:
  name: wiki_daily_100k
  prediction_length: -1
  windows: 1
finetuning:
  batch_size: 64
  checkpoint_to_save: test
  l2_sp_lambda: 0.0001
  learning_rate: 5.0e-06
  path_to_save_all: null
  time_limit: 1800
  update_every_n_steps: 2
  validation:
    early_stopping:
      max_patience: 200
      min_patience: 100
    ts_val_amount: 100
    validate_every_n_steps: 20
  weight_decay: 0.0
