datasets:
- max_context_length: 4096
  name: hospital
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: car_parts_with_missing
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: monash_nn5_weekly
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: solar/W
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: electricity/W
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: ett1/W
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
- max_context_length: 4096
  name: ett2/W
  prediction_length: -1
  ts_amount_limit: 5000
  windows: 1
finetuning:
  batch_size: 2
  checkpoint_to_save: finetuned_model
  l2_sp_lambda: 0.0
  learning_rate: 5.0e-05
  path_to_save_all: null
  time_limit: 2400
  update_every_n_steps: 2
  validation:
    early_stopping:
      max_patience: 200
      min_patience: 100
    ts_val_amount: 100
    validate_every_n_steps: 10
  weight_decay: 0.0
prior:
  context_length:
    end: null
    start: null
    step: null
  context_lengths: []
  enabled: false
  frequencies:
  - 1
  - 2
  - 3
  - 4
  - 5
